### ISSUE TITLE
[ 7. TRABALHE CONOSCO] Estrutura das páginas

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/travelex#11]
## 7. Trabalhe conosco

<img width="528" alt="Captura de Tela 2021-10-21 às 17 24 14" src="https://user-images.githubusercontent.com/82957414/138351614-81521faf-19ca-4bc2-bffa-057e0a00b1e4.png">

- [x] Imagem estática de fundo
- [x] Página única, dividida em duas colunas

coluna da esquerda: 

- [x] Título: Trabalhe conosco
- [x] Texto curto cta
- [x] texto muda para mensagem de confirmação de envio de formulário após clique em enviar no formulário

coluna da direita: 

- [x] formulário em si
- [x] Campos do formulário: nome completo, email, área de atuação, anexo e mensagem. 
- [x] botão enviar branco com hover 
- [ ] Formulário Integrado a serviço contrado pelo cliente (checando qual)

**Comment by guigallo** [comment]
locked by #8
