### ISSUE TITLE
[HOME] background com vídeo placeholder de SP vista aérea em autoplay em loop

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/travelex#17]
A página inicial na verdade é pra ser um vídeo em loop e auto play.

**Comment by guigallo** [comment]
@brunacabeco video em background na página inicial inteira? ou apenas na primeira parte?
tem o link do vídeo?

**Comment by brunacabeco** [comment]
> locked @brunacabeco video em background na página inicial inteira? ou apenas na primeira parte? tem o link do vídeo?

apenas na primeira parte. 
esse funciona para teste? https://drive.google.com/file/d/14zBzpginxywkhH2qADevG0nSCcZKL5QN/view?usp=sharing
