### ISSUE TITLE
Header que troca de cor

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/travelex#18]
- Logo e menu brancos em HOME, RODAPÉ e na PRIMEIRA PÁGINA DE INSTITUCIONAL
  - Logo colorida e menu azul nas demais páginas

página institucional:
<img width="525" alt="Captura de Tela 2021-10-19 às 14 09 30" src="https://user-images.githubusercontent.com/82957414/137962781-21eb0018-ca28-492e-83c0-81a1a3b53ad4.png">

<img width="422" alt="Captura de Tela 2021-10-19 às 14 16 17" src="https://user-images.githubusercontent.com/82957414/137963009-def84f60-94ad-41ef-9052-26b306fbff6e.png">

**Comment by guigallo** [comment]
Cinza Fonte Menu #bebebe
Azul Menu Titulos #221f42
Logo colorida menu: https://drive.google.com/file/d/1jnA0hGbBjGYhMLoDytZF1CtxK5a6ykYI/view?usp=sharing

**Comment by brunacabeco** [comment]
@guigallo está funcionando super bem, mas as cores estão erradas. Na capa, o cabeçalho é totalmente branco (atualmente está cinza), quando fica colorido, o hover é azul (então, apenas 'Institucional' fica azul, e o restante do menu é cinza).
<img width="687" alt="Captura de Tela 2021-11-14 às 20 09 06" src="https://user-images.githubusercontent.com/82957414/141702472-41e0fb05-20c6-440d-9383-1b20d616aec6.png">

**Comment by brunacabeco** [comment]
> @guigallo está funcionando super bem, mas as cores estão erradas. Na capa, o cabeçalho é totalmente branco (atualmente está cinza), quando fica colorido, o hover é azul (então, apenas 'Institucional' fica azul, e o restante do menu é cinza). <img alt="Captura de Tela 2021-11-14 às 20 09 06" width="687" src="https://user-images.githubusercontent.com/82957414/141702472-41e0fb05-20c6-440d-9383-1b20d616aec6.png">

@guigallo viu isso aqui?

**Comment by guigallo** [comment]
preciso de mais informações

**Comment by guigallo** [comment]
banner

#1
logo colorida
texto azul
hover cinza

#2
logo colorida
texto cinza
hover azul

#3
inteiro branco
hover azul

##
pagina ativa - cor do hover
abra sua conta
	branco - primeiro banner/rodapé
	demais - bg azul

#3
	tudo branco/hover cinza

#1
	abra sua conta
	cambio

#2
	intitucional
	cambios
