### ISSUE TITLE
Ajustar dúvidas frequentes da home e da página de dúvidas frequentes

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/travelex#38]
<img width="431" alt="Captura de Tela 2021-11-24 às 12 34 56" src="https://user-images.githubusercontent.com/82957414/143268385-9ef13053-83a8-484e-8ba4-ffcbf2daf705.png">
<img width="1280" alt="Captura de Tela 2021-11-24 às 12 34 46" src="https://user-images.githubusercontent.com/82957414/143268392-34675074-7fd9-4d18-928e-a2e0588a06a9.png">

**Comment by guigallo** [comment]
@brunacabeco mandei direto na main

**Comment by brunacabeco** [comment]
> @brunacabeco mandei direto na main

Show! Pode fechar essa issue
