### ISSUE TITLE
Conteúdos de Câmbio, Ouvidoria e Compliance em markdown

### ISSUE THREAD

**Issue by guigallo** [germanodusha/travelex#41]
- [x] Câmbio
- [x] Ouvidoria
- [x] Compliance

**Comment by brunacabeco** [comment]
@guigallo Eu não consigo checar se foi realmente essa issue, mas me confirma se todo o conteúdo das páginas de câmbio está em markdown? é preciso que esteja, principalmente, o conteúdo da parte de fundo branco abaixo. Se já estiver, pode dar merge :) 

<img width="859" alt="Captura de Tela 2021-12-28 às 10 58 24" src="https://user-images.githubusercontent.com/82957414/147573775-d65c2c00-822e-4bd3-bf60-a1fff47fee39.png">
