### ISSUE TITLE
[HEADER] Menu - Estrutura das páginas

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/travelex#5]
## Menu
<img width="244" alt="Captura de Tela 2021-10-15 às 15 40 52" src="https://user-images.githubusercontent.com/82957414/137536881-6c867161-588c-4a67-9742-2cd33f51cc90.png">

- [x]  Fixo no cabeçalho em todas as páginas
- [x] 6 botões: Home, Institucional, Câmbio Corporativo, Câmbio Pessoa Física, Blog e Abra sua conta
- [x] Marcação (um tracinho) vertical antes de 'Home'
- [x] Marcação (um tracinho) vertical antes de 'Abra sua conta'
- [x] Câmbio corporativo e Câmbio Pessoa física com submenu

Submenu 
<img width="656" alt="Captura de Tela 2021-10-15 às 15 41 12" src="https://user-images.githubusercontent.com/82957414/137540874-1f3ef674-6174-4af9-adc3-26704ae81ce1.png">

- [x] abre se passar mouse em cima
- [x] bloco branco translucido na largura da página

**com os seguintes botões (caminhos):**

- [x]  **Home** (clique retorna para home)
- [x]  **Institucional** (abre página institucional)
- [x]  **Câmbio Corporativo** (hover com submenu. Clique direto em 'Câmbio Corporativo', abre a página com a descrição do primeiro serviço da lista. Caso o usuário clique direto, através do submenu, em algum dos serviços, é direcionado para a página de câmbio corporativo com a descrição do serviço escolhido já aberta)
   submenu:
   - [x] Trade Finance (clique abre direto página com a descrição do serviço)
   - [x] Trade Service (clique abre direto página com a descrição do serviço)
   - [x] Análises, registros e declarações (clique abre direto página com a descrição do serviço)
   - [x] Hedge (clique abre direto página com a descrição do serviço)
   - [x] Assessoria e serviços (clique abre direto página com a descrição do serviço)
- [x]  **Câmbio Pessoa Física** hover com submenu. Clique direto em 'Câmbio Corporativo', abre a página com a descrição do primeiro serviço da lista. Caso o usuário clique direto, através do submenu, em algum dos serviços, é direcionado para a página de câmbio corporativo com a descrição do serviço escolhido já aberta)
   submenu:
   - [x] Câmbio Turismo (abre página do serviço)
   - [x] Transferências Internacionais (abre página do serviço)
   - [x] Pagamentos Internacionais (abre página do serviço)
   - [x] Hedge (abre página do serviço)
- [x]  **Blog** (link direto com o blog da travelex)
- [x] **Abra sua conta** (abre página abra sua conta)

**Comment by guigallo** [comment]
#43
