### ISSUE TITLE
[5. ABRA SUA CONTA]

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/travelex#8]
## 5. Abra sua conta
<img width="648" alt="Captura de Tela 2021-10-19 às 20 01 14" src="https://user-images.githubusercontent.com/82957414/138002425-56997edf-8721-4c31-85b8-7ab724f6680e.png">

- [x] Imagem estática de fundo
- [x] hover azul em 'Abra sua conta' no menu
<img width="439" alt="Captura de Tela 2021-10-19 às 20 02 15" src="https://user-images.githubusercontent.com/82957414/138002472-9da96645-0259-4c06-b324-cef926f477c1.png">

- [x] Página única, dividida em duas colunas

coluna da esquerda: 

- [x] Texto curto CTA sobre abertura de conta
- [x] texto muda para mensagem de confirmação de envio de formulário após clique em enviar no formulário

coluna da direita: 

- [x] Botões 'Corporativo" e "Pessoa Física" com hover de tracinho em baixo, que muda estrutura do  formulário
   - <img width="161" alt="Captura de Tela 2021-10-19 às 20 02 27" src="https://user-images.githubusercontent.com/82957414/138002450-98a83c02-2ead-4745-8fa6-52550f8899d0.png">

- [x] formulário em si
- [x] campos Pessoa física: Nome completo, telefone, email, cpf
- [x] campos Pessoa jurídica: CNPJ, CPF do representante, nome representante, email representante, razão social
- [x] botão enviar branco com hover 

- [ ] Formulário Integrado a serviço contrado pelo cliente (checando qual)

**Comment by guigallo** [comment]
@brunacabeco 

`hover azul em 'Abra sua conta' no menu` - sempre azul quando esta na página, e não só no hover?

`texto muda para mensagem de confirmação de envio de formulário após clique em enviar no formulário` o ideia é o texto de confirmação ficar no lugar do form, quando enviado

**Comment by brunacabeco** [comment]
> @brunacabeco
> 
> `hover azul em 'Abra sua conta' no menu` - sempre azul quando esta na página, e não só no hover?
 Isso! sempre azul quando está na página.
> 
> `texto muda para mensagem de confirmação de envio de formulário após clique em enviar no formulário` o ideia é o texto de confirmação ficar no lugar do form, quando enviado
se for mais simples, sem problemas! Pode colocar no lugar no formulário.
